# Generated by Django 3.2.15 on 2023-04-23 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('JUNIOR', 'Junior level'), ('MIDDLE', 'Middle level'), ('SENIOR', 'Senior level')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
