# Generated by Django 3.2.15 on 2023-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20230427_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
