# Generated by Django 3.2.15 on 2023-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_alter_mentor_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='experience',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
