# Generated by Django 3.2.15 on 2023-06-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_mentor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
