# Generated by Django 3.2.15 on 2023-06-04 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentors', '0006_alter_mentor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='grade',
            field=models.CharField(blank=True, choices=[('Junior level', 'JUNIOR'), ('Middle level', 'MIDDLE'), ('Senior level', 'SENIOR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='users.user'),
            preserve_default=False,
        ),
    ]
