# Generated by Django 3.2.15 on 2023-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_auto_20230604_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='location',
            field=models.CharField(blank=True, choices=[('Junior level', 'JUNIOR'), ('Middle level', 'MIDDLE'), ('Senior level', 'SENIOR')], max_length=100, null=True),
        ),
    ]
