# Generated by Django 3.2.15 on 2023-06-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_mentor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='profile_picture',
            field=models.ImageField(upload_to='src/static/images/'),
        ),
    ]
